
CREATE DATABASE CashierApp;
USE CashierApp;



CREATE TABLE Employees (
    EmployeeID INT AUTO_INCREMENT PRIMARY KEY ,
    FullName VARCHAR(100) NOT NULL ,
    EmployeeRole VARCHAR(30),
    PhoneNumber VARCHAR(15),
    Email VARCHAR(30),
    Salary DECIMAL(7,2),
    HireDate Date,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE Customers(
    CustomerID INT AUTO_INCREMENT PRIMARY KEY  ,
    CustomerName VARCHAR(50) NOT NULL , 
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE CATEGORIES(
    CategoryID INT AUTO_INCREMENT PRIMARY KEY , 
    NAME VARCHAR(50) NOT NULL,
    CategoryDescription VARCHAR(500),
    CategoryItem VARCHAR(50)
    );

CREATE TABLE products(
    ProductID INT AUTO_INCREMENT PRIMARY KEY , 
    CategoryID INT,
    NAME  VARCHAR(50) NOT NULL, 
    PRICE DECIMAL(5,2) NOT NULL,
    Description TEXT,
    StockQuantity INT,
    CreatedAt TIMESTAMP CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP CURRENT_TIMESTAMP ON UPDATE TIMESTAMP CURRENT_TIMESTAMP
    );

CREATE TABLE ORDERS (
    OrderID INT AUTO_INCREMENT PRIMARY KEY , 
    EmployeeID INT NOT NULL, 
    CustomerID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PaymentStatus ENUM('Pending','Paid','Canceled') DEFAULT 'Panding',
    TotalAmount DECIMAL(9,2) NOT NULL,
    DiscountApplied DECIMAL(9,2)
    );

CREATE TABLE ORDERITEM (
    OrderItemID INT AUTO_INCREMENT PRIMARY KEY , 
    EmployeeID INT NOT NULL, 
    CustomerID INT NOT NULL,
    ProductID INT NOT NULL,
    ORDERID INT NOT NULL  , 
    ItemPrice DECIMAL(9,2),
    ItemQuantity INT NOT NULL,
    ItemTotalPrice DECIMAL(9,2)
    );

CREATE TABLE DISCOUNT(
    DiscountID INT AUTO_INCREMENT PRIMARY KEY , 
    ORDERID INT NOT NULL,
    DiscountValue DECIMAL(9,2),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE INVENTORIES(
    InventoryID INT AUTO_INCREMENT PRIMARY KEY, 
    ProductID INT NOT NULL, 
    STOCK INT
    );

CREATE TABLE PAYMENTS (
    PaymentID INT AUTO_INCREMENT PRIMARY KEY, 
    OrderID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAYMENTTYPE ENUM('Cash','Credit') DEFAULT 'Cash', 
    PaymentValue DECIMAL(9,2) NOT NULL    
    );
